# Generated by Django 3.1.7 on 2021-02-26 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('meat_type', models.CharField(choices=[('CK', 'Chicken'), ('BF', 'Beef'), ('PK', 'Pork'), ('FH', 'Fish'), ('GM', 'Game')], default='BF', max_length=2)),
                ('meat_cut', models.CharField(max_length=100)),
                ('cooktime', models.CharField(max_length=100)),
                ('temp', models.CharField(max_length=100)),
                ('credit', models.CharField(max_length=100)),
                ('photo_url', models.TextField()),
                ('desc', models.TextField()),
                ('instructions', models.TextField()),
            ],
        ),
    ]
